### ISSUE TITLE
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502

### ISSUE THREAD

**Issue by r-hou** [ymmmmmmmm/getgrass_bot#1]
Many thanks for the script! In the earlier of the day, I encountered a problem, "websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 502", seems we cannot connect to the server, could you please have a look at it?

**Comment by ymmmmmmmm** [comment]
HTTP 502, if there is no problem with the sock proxy, then there is a high probability that there is a problem with the getgrass server. The script will automatically reconnect. Please run it for a long time to observe the situation.

**Comment by Vsuzie** [comment]
same question
