### ISSUE TITLE
its' okay?

### ISSUE THREAD

**Issue by youngbloodes** [ymmmmmmmm/getgrass_bot#17]
sometimes a new ip address is added to the dashboard, but is this error ok?
![изображение_2024-04-03_035542000](https://github.com/ymmmmmmmm/getgrass_bot/assets/136193213/2eff5703-b5d9-40d6-a3b7-a4b424a9251b)

**Comment by milkthecow-moo** [comment]
This means your ip is banned for one reason or another. You need to go get a new IP.
