### ISSUE TITLE
Dont increase point when run on VPS

### ISSUE THREAD

**Issue by hauchu1196** [ymmmmmmmm/getgrass_bot#2]
I try run on VPS with no_proxy.py and dont increase point. But i try run my desktop with 100 device_id same IP still increase point.
Why run on VPS dont increase point?

**Comment by ymmmmmmmm** [comment]
> I try run on VPS with no_proxy.py and dont increase point. But i try run my desktop with 100 device_id same IP still increase point. Why run on VPS dont increase point?

The vps IP cannot be used, please use a residential proxy IP
