### ISSUE TITLE
运行一会会出现no close frame received or sent的错误，报错信息如下

### ISSUE THREAD

**Issue by Zhenghao-11** [ymmmmmmmm/getgrass_bot#3]
Task exception was never retrieved
future: <Task finished name='Task-198' coro=<connect_to_wss.<locals>.send_ping() done, defined at D:\pythonproject\getgrass.py:33> exception=ConnectionClosedError(None, None, None)>
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 968, in transfer_data
    message = await self.read_message()
  File "D:\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 1038, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "D:\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 1113, in read_data_frame
    frame = await self.read_frame(max_size)
  File "D:\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 1170, in read_frame
    frame = await Frame.read(
  File "D:\Anaconda3\lib\site-packages\websockets\legacy\framing.py", line 69, in read
    data = await reader(2)
  File "D:\Anaconda3\lib\asyncio\streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\pythonproject\getgrass.py", line 38, in send_ping
    await websocket.send(send_message)
  File "D:\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "D:\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent

**Comment by ymmmmmmmm** [comment]
> Task exception was never retrieved future: <Task finished name='Task-198' coro=<connect_to_wss..send_ping() done, defined at D:\pythonproject\getgrass.py:33> exception=ConnectionClosedError(None, None, None)> Traceback (most recent call last): File "D:\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 968, in transfer_data message = await self.read_message() File "D:\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 1038, in read_message frame = await self.read_data_frame(max_size=self.max_size) File "D:\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 1113, in read_data_frame frame = await self.read_frame(max_size) File "D:\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 1170, in read_frame frame = await Frame.read( File "D:\Anaconda3\lib\site-packages\websockets\legacy\framing.py", line 69, in read data = await reader(2) File "D:\Anaconda3\lib\asyncio\streams.py", line 721, in readexactly raise exceptions.IncompleteReadError(incomplete, n) asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "D:\pythonproject\getgrass.py", line 38, in send_ping await websocket.send(send_message) File "D:\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 635, in send await self.ensure_open() File "D:\Anaconda3\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open raise self.connection_closed_exc() websockets.exceptions.ConnectionClosedError: no close frame received or sent

这是由于代理不稳定造成的报错,代码会自动重连,如果不是一直高频率出现忽略即可,或请更换质量稍好的sock代理
