### ISSUE TITLE
带界面版本如何使用

### ISSUE THREAD

**Issue by YiChEeeNNN** [ymmmmmmmm/getgrass_bot#4]
带界面版本如何使用

**Comment by ymmmmmmmm** [comment]
> 带界面版本如何使用

输入正确的userid 和sock5代理点击开始操作即可

**Comment by ymmmmmmmm** [comment]
> 带界面版本如何使用

下载链接
https://github.com/ymmmmmmmm/getgrass_bot/releases/tag/New
